# training settings
batch_size: 32
num_epochs: 100
learning_rate: 0.0003
weight_decay: 0.0001              # 加入
early_stop_patience: 10

# scheduler
scheduler: reduce_on_plateau      # 加入
scheduler_patience: 3             # 加入
scheduler_factor: 0.5             # 加入

# loss function
loss_function: focal              # 加入 (方便之後切換 loss)
focal_gamma: 2.0                  # 加入 focal loss 參數
focal_alpha: 1.0                  # 可選擇加入

# model
model_name: resnext101_32x8d
image_size: 224
num_classes: 100
device: cuda
freeze_backbone: false

# data paths
train_dir: ../data/train
val_dir: ../data/val
test_dir: ../data/test
