# training settings
batch_size: 64
num_epochs: 100
learning_rate: 0.0003
weight_decay: 0.0001              
early_stop_patience: 10

# scheduler
scheduler: reduce_on_plateau      
scheduler_patience: 3             
scheduler_factor: 0.5             

# loss function
loss_function: focal              
focal_gamma: 2.0                  
focal_alpha: 1.0                  

# model
model_name: resnext101_32x8d
image_size: 224
num_classes: 100
device: cuda
freeze_backbone: false

# data paths
train_dir: ../data/train
val_dir: ../data/val
test_dir: ../data/test

use_se: True
